version: "3.7"

services:
  postgres:
    extends:
      file: docker-compose-app.yml
      service: postgres

  redis:
    extends:
      file: docker-compose-app.yml
      service: redis

  worker:
    build:
      context: ./api
      target: api-flask
    working_dir: /usr/src/app
    container_name: pc-worker
    command: >
      bash -c "set -x;
              pip install -e .
              pip install -r ./requirements.txt;
              flask worker;"
    volumes:
      - ./api:/usr/src/app
    env_file:
      - env_file
      - ${ENV:-development}_env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres
      - redis

  worker_low:
    build:
      context: ./api
      target: api-flask
    working_dir: /usr/src/app
    container_name: pc-worker-low
    command: >
      bash -c "set -x;
              pip install -e .
              pip install -r ./requirements.txt;
              flask worker low;"
    volumes:
      - ./api:/usr/src/app
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres
      - redis

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
