version: "3.7"

services:
  flask-metabase:
    build:
      context: ./api
      target: api-flask
    container_name: pc-flask-metabase
    command: >
      bash -c "set -x;
               cd /usr/src/app;
               pip install -r ./requirements.txt;
               python src/pcapi/scripts/pc.py install_data_for_metabase;
               python src/pcapi/scripts/pc.py sandbox -n industrial"
    volumes:
      - ./api:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://pass_culture:passq@postgres-product/pass_culture
      - MAILJET_API_KEY=$MAILJET_API_KEY
      - MAILJET_API_SECRET=$MAILJET_API_SECRET
      - SUPPORT_EMAIL_ADDRESS=$SUPPORT_EMAIL_ADDRESS
      - ADMINISTRATION_EMAIL_ADDRESS=$ADMINISTRATION_EMAIL_ADDRESS
      - DEV_EMAIL_ADDRESS=$DEV_EMAIL_ADDRESS
    networks:
      - db_nw
    depends_on:
      - postgres-product

  postgres-product:
    image: postgres:12.3-alpine
    container_name: pc-postgres-product
    volumes:
      - postgres_product:/var/lib/postgresql/data
    env_file:
      - env_file
    networks:
      - db_nw
    ports:
      - 5435:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  postgres-metabase:
    image: postgres:12.3-alpine
    container_name: pc-postgres-metabase
    volumes:
      - postgres_metabase:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pass_culture
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
    networks:
      - db_nw
    ports:
      - 5436:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on


  metabase-app:
    container_name: pc-metabase-app
    image: metabase/metabase
    ports:
      - 3002:3000
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: pass_culture
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres-metabase
    depends_on:
      - postgres-metabase
    links:
      - postgres-metabase
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge

volumes:
  postgres_product:
  postgres_metabase:
  metabase_data:
