# Default values for passculture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The rest of the values are in pass-culture-deployment repository
# Only set secret keys in this file

secrets:
  - name: ADMINISTRATION_EMAIL_ADDRESS
  - name: ALGOLIA_API_KEY
  - name: ALGOLIA_APPLICATION_ID
  - name: ALLOCINE_API_KEY
  - name: APPS_FLYER_ANDROID_API_KEY
  - name: APPS_FLYER_IOS_API_KEY
  - name: BACKOFFICE_USER_EMAIL
  - name: BATCH_SECRET_API_KEY
  - name: BLACKLISTED_SMS_RECIPIENTS
  - name: CDS_API_URL
  - name: CLOUD_TASK_BEARER_TOKEN
  - name: COMPLIANCE_EMAIL_ADDRESS
  - name: DATABASE_URL
  - name: DEV_EMAIL_ADDRESS
  - name: FINANCE_GOOGLE_DRIVE_ROOT_FOLDER_ID
  - name: FLASK_SECRET
  - name: GCP_BUCKET_CREDENTIALS
  - name: GCP_DATA_BUCKET_NAME
  - name: GCP_DATA_PROJECT_ID
  - name: GOOGLE_CLIENT_ID
  - name: GOOGLE_CLIENT_SECRET
  - name: JWT_SECRET_KEY
  - name: NOTION_TOKEN
  - name: OBJECT_STORAGE_URL
  - name: OUTSCALE_ACCESS_KEY
  - name: OUTSCALE_SECRET_KEY
  - name: RECAPTCHA_SECRET
  - name: REDIS_URL
  - name: REPORT_OFFER_EMAIL_ADDRESS
  - name: SENDINBLUE_API_KEY
  - name: SENTRY_DSN
  - name: SLACK_BOT_TOKEN
  - name: SUPPORT_EMAIL_ADDRESS
  - name: SUPPORT_PRO_EMAIL_ADDRESS
  - name: USER_PROFILING_API_KEY
  - name: USER_PROFILING_ORG_ID
  - name: USER_PROFILING_URL
