apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: testing-pcapi-pgsql
  namespace: pcapi-pr-${PRID}
spec:
  refreshInterval: "1m"
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: pcapi-pullrequest_pgsql_pwd
      secretKey: PGSQL_PWD
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key:  pcapi-pullrequest_pgsql_user
      secretKey: PGSQL_USER
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key:  pcapi-pullrequest_pgsql_db_name
      secretKey: DB_NAME
  secretStoreRef:
    kind: ClusterSecretStore
    name: testing-clustersecretstore
  target:
    name: testing-pcapi-pgsql
