# Default values for passculture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gcp:
  projectId: passculture-metier-ehp
  appName: pcapi-perf

image:
  repository: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-artifact-registry/pcapi
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: metier-perf-pcapi@passculture-metier-ehp.iam.gserviceaccount.com

### API deployment ###
api:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 6
    maxReplicas: 20
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.perf.internal-passculture.app
        paths:
          - path: /
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.perf.internal-passculture.app

### High Latency API deployment ###
highLatencyApi:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.perf.internal-passculture.app
        paths:
          - path: /bookings/pro$
          - path: /offers$
          - path: /offers/all-active-status$
          - path: /offerers$
          - path: /offerers/(.*)$
          - path: /venues$
          - path: /venues/(.*)/stats$
          - path: /venueProviders$
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.perf.internal-passculture.app

### Admin deployment ###
admin:
  enabled: false

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  replicaCount: 1

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.perf.internal-passculture.app
        paths:
          - path: /pc/back-office/
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.perf.internal-passculture.app

### Worker deployment ###
workers:
  - name: worker
    enabled: true
    replicaCount: 1
    command:
      - flask
    args:
      - worker
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 384Mi
  - name: worker-low
    enabled: true
    replicaCount: 1
    command:
      - flask
    args:
      - worker
      - low
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 384Mi
  - name: worker-idcheck
    enabled: true
    replicaCount: 2
    command:
      - flask
    args:
      - worker
      - id_check
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 384Mi

### Cron deployments ###
crons:

  replicaCount: 1

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 768Mi

  cron:
    import_users:
      enabled: false
      command:
        - python
      args:
        - echo
        - "Wrong_Env"
    clock:
      enabled: false
      command:
        - flask
      args:
        - clock
    algolia:
      enabled: false
      command:
        - flask
      args:
        - algolia_clock
    titelive:
      enabled: false
      command:
        - flask
      args:
        - titelive_clock
    sandbox_deployer:
      enabled: false

### Console deployment ###
console:
  enabled: true

  replicaCount: 1

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi


# Deployment specific for uploading the identity_document
# the route is /native/v1/identity_document
uploadIdentityDocument:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.perf.internal-passculture.app
        paths:
          - path: /native/v1/identity_document$
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.perf.internal-passculture.app

# Deployment for all cloud tasks
cloudTasks:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.perf.internal-passculture.app
        paths:
          - path: /cloud-tasks/(.*)$
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.perf.internal-passculture.app

aide:
  enabled: false

configmapApi:
   DATABASE_STATEMENT_TIMEOUT: 60000

configmap:
  ENV: testing
  GUNICORN_PORT: 5000
  GUNICORN_MAX_REQUESTS: 3000
  GUNICORN_MAX_REQUESTS_JITTER: 10
  GUNICORN_WORKERS: 2
  GUNICORN_THREADS: 5
  GUNICORN_TIMEOUT: 90
  GUNICORN_LOG_LEVEL: info
  DATABASE_IDLE_IN_TRANSACTION_SESSION_TIMEOUT: "1800000"

configmapCloudTasks:
  GUNICORN_THREADS : 10

configmapUploadIdentityDocument:
  GUNICORN_THREADS: 10

secrets:
  - name: ADMINISTRATION_EMAIL_ADDRESS
    version: 1
  - name: ALGOLIA_API_KEY
    version: 1
  - name: ALGOLIA_APPLICATION_ID
    version: 1
  - name: ALLOCINE_API_KEY
    version: 2
  - name: BATCH_SECRET_API_KEY
    version: 1
  - name: CLOUD_TASK_BEARER_TOKEN
    version: 1
  - name: COMPLIANCE_EMAIL_ADDRESS
    version: 1
  - name: DATABASE_URL
    version: 1
  - name: DEMARCHES_SIMPLIFIEES_TOKEN
    version: 1
  - name: DEMARCHES_SIMPLIFIEES_WEBHOOK_TOKEN
    version: 1
  - name: DEV_EMAIL_ADDRESS
    version: 1
  - name: EXPORT_TOKEN
    version: 1
  - name: FLASK_SECRET
    version: 1
  - name: FTP_TITELIVE_PWD
    version: 1
  - name: FTP_TITELIVE_URI
    version: 1
  - name: FTP_TITELIVE_USER
    version: 1
  - name: GCP_ASSETS_BUCKET_NAME
    version: 1
  - name: JOUVE_API_DOMAIN
    version: 1
  - name: JOUVE_PASSWORD
    version: 1
  - name: JOUVE_USERNAME
    version: 1
  - name: JOUVE_VAULT_GUID
    version: 1
  - name: JWT_SECRET_KEY
    version: 1
  - name: MAILJET_API_KEY
    version: 1
  - name: MAILJET_API_SECRET
    version: 1
  - name: NATIVE_RECAPTCHA_SECRET
    version: 1
  - name: OBJECT_STORAGE_PROVIDER
    version: 1
  - name: OVH_BUCKET_NAME
    version: 1
  - name: OVH_PASSWORD
    version: 1
  - name: OVH_REGION_NAME
    version: 1
  - name: OVH_TENANT_NAME
    version: 1
  - name: OVH_USER
    version: 1
  - name: PASS_CULTURE_BIC
    version: 1
  - name: PASS_CULTURE_IBAN
    version: 1
  - name: PASS_CULTURE_REMITTANCE_CODE
    version: 1
  - name: PAYMENTS_DETAILS_RECIPIENTS
    version: 1
  - name: PAYMENTS_REPORT_RECIPIENTS
    version: 1
  - name: PC_GOOGLE_KEY
    version: 1
  - name: PC_GOOGLE_KEY_64
    version: 1
  - name: PROVIDER_FNAC_BASIC_AUTHENTICATION_TOKEN
    version: 1
  - name: RECAPTCHA_SECRET
    version: 1
  - name: REDIS_URL
    version: 1
  - name: SENDINBLUE_API_KEY
    version: 2
  - name: SENTRY_DSN
    version: 2
  - name: SUPPORT_EMAIL_ADDRESS
    version: 1
  - name: TRANSACTIONS_RECIPIENTS
    version: 1
  - name: WALLET_BALANCES_RECIPIENTS
    version: 1
  - name: WHITELISTED_EMAIL_RECIPIENTS
    version: 1
  - name: WHITELISTED_INE_HASHES
    version: 1
  - name: WHITELISTED_SMS_RECIPIENTS
    version: 1
