# Default values for passculture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gcp:
  projectId: passculture-metier-ehp
  appName: pcapi-integration

image:
  repository: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-artifact-registry/pcapi
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: metier-integration-pcapi@passculture-metier-ehp.iam.gserviceaccount.com

### API deployment ###
api:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.passculture-integration.beta.gouv.fr
        paths:
          - path: /
      - host: backend.integration.passculture.app
        paths:
          - path: /
      - host: backend.integration.passculture.pro
        paths:
          - path: /
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.passculture-integration.beta.gouv.fr
      - backend.integration.passculture.app
      - backend.integration.passculture.pro

### High Latency API deployment ###
highLatencyApi:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.passculture-integration.beta.gouv.fr
        paths:
          - path: /bookings/pro$
          - path: /offers$
          - path: /offers/all-active-status$
          - path: /offerers$
          - path: /venues$
          - path: /venues/(.*)/stats$
          - path: /venueProviders$
      - host: backend.integration.passculture.app
        paths:
          - path: /bookings/pro$
          - path: /offers$
          - path: /offers/all-active-status$
          - path: /offerers$
          - path: /venues$
          - path: /venues/(.*)/stats$
          - path: /venueProviders$
      - host: backend.integration.passculture.pro
        paths:
          - path: /bookings/pro$
          - path: /offers$
          - path: /offers/all-active-status$
          - path: /offerers$
          - path: /venues$
          - path: /venues/(.*)/stats$
          - path: /venueProviders$
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.passculture-integration.beta.gouv.fr
      - backend.integration.passculture.app
      - backend.integration.passculture.pro

### Admin deployment ###
admin:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  replicaCount: 1

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.passculture-integration.beta.gouv.fr
        paths:
          - path: /pc/back-office/
      - host: backend.integration.passculture.app
        paths:
          - path: /pc/back-office/
      - host: backend.integration.passculture.pro
        paths:
          - path: /pc/back-office/
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.passculture-integration.beta.gouv.fr
      - backend.integration.passculture.app
      - backend.integration.passculture.pro

### Worker deployment ###
workers:
  - name: worker
    enabled: true
    replicaCount: 1
    command:
      - python
    args:
      - src/pcapi/workers/worker.py
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 384Mi
  - name: worker-low
    enabled: true
    replicaCount: 1
    command:
      - python
    args:
      - src/pcapi/workers/worker.py
      - low
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 384Mi
  - name: worker-idcheck
    enabled: true
    replicaCount: 1
    command:
      - python
    args:
      - src/pcapi/workers/worker.py
      - id_check
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 384Mi

### Cron deployments ###
crons:

  replicaCount: 1

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 768Mi

  cron:
    import_users:
      enabled: false
      command:
        - echo
      args:
        - "Wrong_Env"
    clock:
      enabled: false
      command:
        - python
      args:
        - src/pcapi/scheduled_tasks/clock.py
    algolia:
      enabled: false
      command:
        - python
      args:
        - src/pcapi/scheduled_tasks/algolia_clock.py
    titelive:
      enabled: false
      command:
        - python
      args:
        - src/pcapi/scheduled_tasks/titelive_clock.py
    sandbox_deployer:
      enabled: false

### Console deployment ###
console:
  enabled: true

  replicaCount: 1

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

###  Cloud task idcheck deployment ###
cloudTaskIdcheck:
  enabled: true

  containerPort : 5000

  probePath: /health/api

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 700m
      memory: 1536Mi

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 70
    # Enable this option to scale on memory percentage
    # targetMemoryUtilization: 70

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: backend.passculture-integration.beta.gouv.fr
        paths:
          - path: /native/v1/identity_document$
          - path: /cloud-tasks/verify_identity_document$
      - host: backend.integration.passculture.app
        paths:
          - path: /native/v1/identity_document$
          - path: /cloud-tasks/verify_identity_document$
      - host: backend.integration.passculture.pro
        paths:
          - path: /native/v1/identity_document$
          - path: /cloud-tasks/verify_identity_document$
    tls:
    - secretName: pcapi-ingress-cert
      hosts:
      - backend.passculture-integration.beta.gouv.fr
      - backend.integration.passculture.app
      - backend.integration.passculture.pro

aide:
  enabled: false

configmapApi:
   DATABASE_STATEMENT_TIMEOUT: 60000

configmap:
  ENV: integration
  NLTK_DATA: /root/nltk_data
  GCP_BUCKET_NAME: passculture-metier-ehp-integration-assets
  GUNICORN_PORT: 5000
  GUNICORN_MAX_REQUESTS: 3000
  GUNICORN_MAX_REQUESTS_JITTER: 10
  GUNICORN_WORKERS: 2
  GUNICORN_THREADS: 5
  GUNICORN_TIMEOUT: 90
  ID_CHECK_MAX_ALIVE_TOKEN: 4
  OBJECT_STORAGE_PROVIDER: OVH,GCP
  NATIVE_APP_MINIMAL_CLIENT_VERSION: "1.142.0"

configmapCloudTaskIdcheck:
  GUNICORN_THREADS : 10

secrets:
  - name: ADMINISTRATION_EMAIL_ADDRESS
    version: 2
  - name: ALGOLIA_API_KEY
    version: 2
  - name: ALGOLIA_APPLICATION_ID
    version: 2
  - name: BATCH_SECRET_API_KEY
    version: 1
  - name: BLACKLISTED_SMS_RECIPIENTS
    version: 1
  - name: DATABASE_URL
    version: 2
  - name: DEV_EMAIL_ADDRESS
    version: 2
  - name: GCP_BUCKET_CREDENTIALS
    version: 1
  - name: FLASK_SECRET
    version: 2
  - name: JWT_SECRET_KEY
    version: 2
  - name: MAILJET_API_KEY
    version: 2
  - name: MAILJET_API_SECRET
    version: 2
  - name: NOTION_TOKEN
    version: 1
  - name: OVH_BUCKET_NAME
    version: 2
  - name: OVH_PASSWORD
    version: 2
  - name: OVH_REGION_NAME
    version: 2
  - name: OVH_TENANT_NAME
    version: 2
  - name: OVH_USER
    version: 2
  - name: PC_GOOGLE_KEY
    version: 4
  - name: PC_GOOGLE_KEY_64
    version: 2
  - name: RECAPTCHA_SECRET
    version: 2
  - name: REDIS_URL
    version: 2
  - name: SENDINBLUE_API_KEY
    version: 2
  - name: SENTRY_DSN
    version: 3
  - name: SUPPORT_EMAIL_ADDRESS
    version: 2
  - name: USER_PROFILING_URL
    version: 2
  - name: USER_PROFILING_ORG_ID
    version: 1
  - name: USER_PROFILING_API_KEY
    version: 1
  - name: APPS_FLYER_ANDROID_API_KEY
    version: 1
  - name: APPS_FLYER_IOS_API_KEY
    version: 1
