pg_version = "15.5"
excluded_rules = [
  # backward compatibility is not needed because we are the only ones using our database
  "adding-required-field",
  "ban-drop-column",
  "ban-drop-not-null",
  "ban-drop-table",
  "renaming-table",
  "renaming-column",
  "prefer-identity",
  # every timestamp is stored as UTC, which is i18n best practice
  "prefer-timestamptz",
  "prefer-identity",
  # timeout is already set globally for each migration
  "require-timeout-settings",
]
