name: Add annotated tag
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches:
      - bsr-add-action-to-mark-issues-as-not-valid
jobs:
  add-annotated-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      # - name: Annotate üöÄ
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     create_annotated_tag: true
      #     tag_prefix: RC-
      #     default_bump: major
      #     fetch_all_tags: true

      # - name: Get release version
      #   id: get_release_version
      #   run: |
      #     VERSION=$(echo ${{ steps.tag_version.outputs.new_version }} | cut -d "." -f 1)
      #     echo "::set-output name=value::$VERSION"
      - name: Setup gajira cli
        uses: atlassian/gajira-cli@master
        with:
          version: 1.0.20
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Get jira issue key in commit
        id: get_jira_key
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: commits
      - name: Get jira issue
        if: ${{ steps.get_jira_key.outputs.issue != null }}
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: jira get ${{ steps.get_jira_key.outputs.issue }}
      - name: Push release candidate to jira issue
        if: ${{ steps.get_jira_key.outputs.issue != null }}
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: echo "toto" # jira edit ${{ steps.get_jira_key.outputs.issue }} --override customfield_10043=${{ steps.get_release_version.outputs.value }} --noedit
