name: "[PRO] Deploy PR version for validation"


on:  
  pull_request:
    paths:
      - 'pro/**'
    branches:
      - master

jobs:  
  deploy-validation-env:
    uses: ./.github/workflows/deploy-pro-pr-version-generic.yml
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
    with:
      ENV: testing
      CHANNEL: ""
