name: Tag and deploy to staging and then to production

on:
  workflow_dispatch:
    inputs:
      releaseCandidateVersion:
        description: "Num√©ro de la RC sans le .0.0 (ex: 2150)"
        required: true
        type: string
      releaseVersion:
        description: "Nom de la release (ex: 199.0.0)"
        required: true
        type: string

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RC
        uses: actions/checkout@v3
        with:
          ref: RC-${{ github.event.inputs.releaseCandidateVersion }}.0.0
      - name: Author
        run: |
          git config --global user.email "github-actions-bot@passculture.app"
          git config --global user.name "${{ github.actor }}"
      - name: Tag Release
        run: |
          ./pc -t ${{ github.event.inputs.releaseVersion }} tag

  deploy-to-staging:
    needs: tag-version
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          ref: v${{ github.event.inputs.releaseVersion }}
      - name: Deploy Release to staging
        run: |
          ./pc -e staging -t ${{ github.event.inputs.releaseVersion }} deploy

  deploy-to-production:
    needs: tag-version
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          ref: v${{ github.event.inputs.releaseVersion }}
      - name: Deploy Release to production
        run: |
          ./pc -e production -t ${{ github.event.inputs.releaseVersion }} deploy
