name: Initiate workflow
# run-name: Test main${{ github.ref == 'refs/heads/master' && ' and deploy to testing' || '' }}

on:
  push:
    branches:
      - master
      - "maint/**"
  pull_request:
    branches-ignore:
      - docs

permissions: write-all

env:
  IS_MES_MEP: ${{ github.ref == 'refs/pull/9823/merge' || startsWith(github.ref,'refs/heads/maint/v') }}

concurrency:
  # cancel previous workflow of the same branch except on master
  group: ${{ github.ref }}
  # cancel-in-progress: ${{ github.ref == 'refs/heads/master' && false || true }}
  cancel-in-progress: ${{ github.ref == 'refs/pull/9823/merge' && false || true }}

jobs:
  echo-github-ref:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ env.IS_MES_MEP }}

  check-api-folder-changes:
    name: Check api folder changes
    uses: ./.github/workflows/dev_on_workflow_check_folder_changes.yml
    with:
      folder: api

  check-pro-folder-changes:
    name: Check pro folder changes
    uses: ./.github/workflows/dev_on_workflow_check_folder_changes.yml
    with:
      folder: pro

  build-api:
    name: Build API (backend) Docker image
    needs:
      - check-api-folder-changes
      - check-pro-folder-changes
    if: |
      needs.check-api-folder-changes.outputs.folder_changed == 'true' ||
      needs.check-pro-folder-changes.outputs.folder_changed == 'true' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref,'refs/heads/maint/v')
    uses: ./.github/workflows/dev_on_workflow_build_and_push_docker_images.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      tag: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      # Needed to run end-to-end tests, i.e. when either "pro" or
      # "api" source code changes, which is the condition under which
      # this step is run. In other words: always.
      pcapi: true
      # Extra when tests are run on master before deployment on testing.
      console: ${{ github.ref == 'refs/heads/master' }}
      # Needed to run backend tests.
      tests: ${{ needs.check-api-folder-changes.outputs.folder_changed == 'true' || github.ref == 'refs/heads/master' || startsWith(github.ref,'refs/heads/maint/v') }}
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

  test-api:
    name: Test api
    needs:
      - check-api-folder-changes
      - build-api
    if: |
      needs.check-api-folder-changes.outputs.folder_changed == 'true' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref,'refs/heads/maint/v')
    uses: ./.github/workflows/dev_on_workflow_tests_api.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

  test-pro:
    needs: check-pro-folder-changes
    if: |
      needs.check-pro-folder-changes.outputs.folder_changed == 'true' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref,'refs/heads/maint/v')
    name: Tests pro
    uses: ./.github/workflows/dev_on_workflow_tests_pro.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
    with:
      CACHE_BUCKET_NAME: passculture-infra-prod-github-runner-cache

  test-pro-e2e:
    needs:
      - check-api-folder-changes
      - check-pro-folder-changes
      - build-api
    if: |
      needs.check-api-folder-changes.outputs.folder_changed == 'true' ||
      needs.check-pro-folder-changes.outputs.folder_changed == 'true' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref,'refs/heads/maint/v')
    name: Tests pro E2E
    uses: ./.github/workflows/dev_on_workflow_tests_pro_e2e.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
    with:
      CACHE_BUCKET_NAME: passculture-infra-prod-github-runner-cache

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    needs: check-pro-folder-changes
    # if: |
    #   github.ref == 'refs/heads/refacto-workflows'
    # if: |
    #   needs.check-pro-folder-changes.outputs.folder_changed == 'true' ||
    #   github.ref == 'refs/heads/master'
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: "pro/.nvmrc"
      # - name: Install tools needed
      #   run: |
      #     apt-get update && apt-get install rsync -y
      - name: Install and Build Storybook üîß
        working-directory: pro
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn build-storybook
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs # The branch the action should deploy to.
          folder: pro/docs-build # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # The folder that we serve our Storybook files from

  dependabot-auto-merge:
    needs:
      - test-pro
    if: |
      github.event_name == 'pull_request' &&
      github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/dev_on_workflow_dependabot_auto_merge.yml

  deploy-to-testing:
    name: Deploy to testing
    needs:
      - test-api
      - test-pro
    if: |
      always() &&
      github.ref == 'refs/heads/master' &&
      (needs.test-api.result == 'success' || needs.test-api.result == 'skipped') &&
      (needs.test-pro.result == 'success' || needs.test-pro.result == 'skipped')
    uses: ./.github/workflows/dev_on_workflow_deploy.yml
    with:
      environment: testing
      app_version: ${{ github.sha }}
      teleport_version: 11.1.1
      teleport_proxy: teleport.ehp.passculture.team:443
      teleport_kubernetes_cluster: passculture-metier-ehp
      deploy_api: ${{ needs.test-api.result == 'success' }}
      deploy_pro: ${{ needs.test-pro.result == 'success' }}
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

  notification:
    name: "Notification"
    runs-on: ubuntu-latest
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    needs:
      - deploy-to-testing
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Authentification to Google
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

      - name: Get Secret
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # channel #alertes-deploiement
          channel-id: "CQAMNFVPS"
          payload: |
            {
            "attachments": [
              {
                "mrkdwn_in": ["text"],
                "color": "#A30002",
                "author_name": "${{github.actor}}",
                "author_link": "https://github.com/${{github.actor}}",
                "author_icon": "https://github.com/${{github.actor}}.png",
                "title": "PCAPI Deployment",
                "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                "text": "Le d√©ploiement de la version `master` a √©chou√© sur `testing` :boom:"
              }
            ],
            "unfurl_links": false,
            "unfurl_media": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
