name: "[on_dispatch] Deploy preview Storybook"

on:
  workflow_dispatch:
    inputs:
      EXPIRES:
        type: string
        default: "2d"

permissions: write-all

jobs:
  build-and-deploy-storybook:
    name: "Build and deploy Storybook"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout ðŸ›Žï¸"
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "OpenID Connect Authentication"
        id: "openid-auth"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: "Get Secret"
        id: "secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v3"
        with:
          secrets: |-
            FIREBASE_TOKEN:passculture-metier-ehp/pc_pro_testing_firebase_json
      - uses: actions/setup-node@v6
        with:
          node-version-file: "pro/package.json"
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@main
      - name: "Install dependencies"
        working-directory: pro
        # we cannot use an action like nick-fields/retry@v3 along with `working-directory`
        run: yarn install --immutable
      - name: "Build Storybook ðŸ”§"
        working-directory: pro
        run: yarn build-storybook
      - name: "Deploy ðŸš€"
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: ${{ steps.secrets.outputs.FIREBASE_TOKEN }}
          expires: ${{ inputs.EXPIRES }}
          projectId: pc-pro-testing
          entryPoint: pro
          channelId: ${{ github.ref_name }}
          target: pc-pro-storybook
      - name: "Publish Summary"
        run: |
          {
            echo "### :rocket: Deploy PRO Storybook Summary"
            echo "| Results                              | Value |"
            echo "| ------------------------------------ | ----- |"
            echo "| [pro] preview url                    |  ${{ steps.firebase-deploy.outputs.details_url }} |"
          } >> $GITHUB_STEP_SUMMARY
